security: 
  basic:  
    enabled: true  
  user:  
    name: fastfood  # 用户名  
    password: Scadmin773577   # 用户密码  
 
# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  environment: prod
  instance:
    hostname: 172.24.226.143
    port: ${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@172.24.226.143:${eureka.instance.port}/eureka/,http://${security.user.name}:${security.user.password}@172.24.226.142:${eureka.instance.port}/eureka/,http://${security.user.name}:${security.user.password}@172.24.226.140:${eureka.instance.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000